language: java
install: true
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2/repository"
deploy:
  provider: releases
  api_key:
    secure: aA01bnXub8QEce4n7IP/Y6+4l7t9f5W4wkb/J0FOJeHL1Vk2+wf+HmoN3Bp75eTSAeOKHACac2jXChYIH+fyyi0sYtayQ/D4DfWK1SwIu61Zza3jJqZJwYYmZwzLmQlRr56kqwlLyYYvTB242e7xTABhs86KxhxIcrq8/4zkpom4RrscrzVGL2XzlDh17S5yNacaE+GlkEa+DgRbF9Jq9n1vlaMNnxBHai1SEkKBpQe5YEs9FRFLdHQ4Jq5uoL9jUQBaW6zwoAf/NSpSGNL9m92p04autyPH7V7N3hCqK5bsPgKgVbN8IHC69IjN1ODzVZs9k+iYyZ+rJEy9gXJ0KwtblqOhKImPe7ad6rXGDXwUJqjU7Mjxg0lClk1ziqPUVZYnd4C6J9aengmC67rkduB/hP4rE6DwXQB0w7ArUQhig1yqher87ziL2nyIcEdGu2PLycTTfZE1vnvw+lP8SBq0SPMspaDjN09jWon65mcn/3c9kzzG3UQXlDvAsdgSN5gmn0QU2LR5FxWn8SQ4pTSAX9vURsLFygHcICyweB7AOQKKsG+F6I0iaYmXBJ4Vp8rMnHcOtkBT1KIMnxIg0L1zt3lrtE9Jzlj9UxPvyFKZRMydB0LxuhxtfGDxp7uctZ5r8LGKwtPcdNvMdl4U34CrwfHSgC4e5SbUU0/hH3A=
  file: "*/target/matchmaking*.jar"
  skip_cleanup: true
  on:
    repo: OrigamiDream/Matchmaking
