language: java
install: true
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2/repository"
deploy:
  provider: releases
  api_key:
    secure: aA01bnXub8QEce4n7IP/Y6+4l7t9f5W4wkb/J0FOJeHL1Vk2+wf+HmoN3Bp75eTSAeOKHACac2jXChYIH+fyyi0sYtayQ/D4DfWK1SwIu61Zza3jJqZJwYYmZwzLmQlRr56kqwlLyYYvTB242e7xTABhs86KxhxIcrq8/4zkpom4RrscrzVGL2XzlDh17S5yNacaE+GlkEa+DgRbF9Jq9n1vlaMNnxBHai1SEkKBpQe5YEs9FRFLdHQ4Jq5uoL9jUQBaW6zwoAf/NSpSGNL9m92p04autyPH7V7N3hCqK5bsPgKgVbN8IHC69IjN1ODzVZs9k+iYyZ+rJEy9gXJ0KwtblqOhKImPe7ad6rXGDXwUJqjU7Mjxg0lClk1ziqPUVZYnd4C6J9aengmC67rkduB/hP4rE6DwXQB0w7ArUQhig1yqher87ziL2nyIcEdGu2PLycTTfZE1vnvw+lP8SBq0SPMspaDjN09jWon65mcn/3c9kzzG3UQXlDvAsdgSN5gmn0QU2LR5FxWn8SQ4pTSAX9vURsLFygHcICyweB7AOQKKsG+F6I0iaYmXBJ4Vp8rMnHcOtkBT1KIMnxIg0L1zt3lrtE9Jzlj9UxPvyFKZRMydB0LxuhxtfGDxp7uctZ5r8LGKwtPcdNvMdl4U34CrwfHSgC4e5SbUU0/hH3A=
  file: "*/target/matchmaking*.jar"
  skip_cleanup: true
  on:
    repo: OrigamiDream/Matchmaking
env:
  global:
    secure: HniZpI7MlP5H3/Ymx0+dzm2UzIU4+LvZXfIsL3bkRTApvrz4d9AO4JUNHMA79gZxhHzz2dOR3bGvj+LJt8Aru+IxGJyWbxppYOO+b/iPjsjisqYpyTSDVSYJsxGxbPwGV8Wd1jhQk3kOVQ19nrTBAZTGBJH1V71cMgXuM3JiaIeebH4pJTvXXuEAhkKAeT3WAAYXld3q5uPTAUpj4zJRQQZbb4I87q7hTS1//r+0+fduTUDXLC926+RRzcgbmBw8VFAF8VCDzGULh79levocqlOwIbhyLwxEHdhVxrpFeuztiiJsK690GXXOwGehllUldWODwYSrQdcQCqqJIUr19p5lAPLxSwMDTvufMLINJ6yeXAPk3QtweVDZXjUZbrksszQQE8fOEKY8Fg4QhpLrTHScO3ES8Hnsg8pz1Dv6bXn5REjPk28GvqX9lNKv/xf1aoShPlyvcdp+XraDryUzaD6Sfw3kLa3DKbCVXq6FIRuJ+YLzsvuqPKTaJrk0J0z6AuM3NKTUGBo7JXF5uDb/4amHuzSmyYSyKSFCZsuWYEwghMQgiKdrU0e29Mv4DBTY03ANIXR+yq26h3NWuoJ+2KfoR54VCcUf8yiogw58ZPNMFgHTDqCBbdmDbhWl4/5H8Unr34XUmxJ8lz+1JypoOGK4tihb+s9JS5rUdkYX5I8=
