language: java
install: true
jdk: openjdk8
dist: trusty
cache:
  directories:
  - "$HOME/.m2/repository"
jobs:travis
  include:
  - stage: test
    script:
    - "./mvnw clean verify"
deploy:
  provider: releases
  api_key:
    secure: "HWuGhh1LN9Mtps8GMTwalEl1QNM+IOkkgB+nxzkO+fVM/alLi+ODCnBKIRbZTXHrWvJAH0KGUzAhTyc8hcuuDEbq04NqoBa9rICxJri96ydPS1Vnwws7iMRlpB22ixY9L0JQUH91FgVWe113D+U6e3A0u2TeaqSHKkTc9oc2D03gy4+Yg8Qa3Je3c8nd715Ynou/LGysnsC9wfuy3b3VYDZS0KqVXLUQkqHeA11ABnJI0ua3+i0roR+WH+P2OP7UIHMPfHasqBVbApWLolYuqt+ZVscunMXpAvC2AomnXAe3ojVzwLArNx7cbPND1vkCYU8IhC5dM8FGvaxD/VYeYQIz5bNKdqgq/4Ax3UFTuh1CVBz58dLVRm5qKdqJXZZHTpTGTPhdfkTu+63esd7tRBHoeLYw60vdr4g2XCZsI0jxmnhzwESxwKxTbWPedacJYj0lEBdjVqFvZCKL3z/SNVpOD7TqHpw7n/K4WoHxuow4I1Bw0J2OIPM5qNXEs7mBnrqlsY42f5FbUKgn+ZUJ2/HVe/lAwLO49lwCLzzRxFKBpsj5CdESVtUWLLtwOp38Y/lufJIuKoev0gE/XbrZ6yaTKGqyDcwkm8E9gpK03AGsQ68fu8r+/I2kx7dcpAOYeQi3odSY7hpaBmslNabw7yXe9pdule9aLwXrUYqJNX0="
  skip_cleanup: true
  file_glob: true
  file: "*/target/matchmaking-.jar"
  on:
    repo: OrigamiDream/Matchmaking
    tags: true