language: java
install: true
jdk: openjdk8
dist: trusty
cache:
  directories:
  - "$HOME/.m2/repository"
jobs:
  include:
  - stage: test
    script:
    - "./mvnw clean verify"
deploy:
  provider: releases
  api_key:
    secure: "Z+KXcFZp4ahGvqLBUG34clSBeNIlFF8cbXzW27HZw/b6bNY60z0p1FdanLx4tnn1YrzCrNF2ojxm/fhTlCjhfdt+rYMOgHZxlbORPsJ4LjjI3Xir12kwbb/BjLekIx2Z0x1TipTR+CJ/NEfbswOSm2XtTIegUjICKI7tFeQUixA7gkS7Z7PZUWDjBeR08sj5zidQfauQaOMgSPwKzBv+q7i2qqMafx0n/8d7nwagg444Tu5PVjLDN4hoIgT+fXleZ9DU36Kkqhiv3m1fcdsXihc99Ukx5X/mJbPGHMNj7/ZE+UQOZavR9ETi/8U+z6IC5LVfsvGUJp/wyKCCF86zUH9D0u9rsTMnvd/ethkQJWnZ5C4DFhmaiC5cOr3xZ3I4xriRPVWT377/J1L3U8vL3rxz6+4++TxCb6KUt8Ul6KmqudIZvPSA/FhKD8vyY+Aozs10rak7jmEbYGWLKfuRgCmkFJR2+a5nfuyb7ghcsNkdEoTzOmbiaSzZBR8lhofBAjwr/rjbXYyO3A9Yb5dxzcVvchIsOWSGHwQasNW3YgPfeLstFGvX4525ZmKpH7NvpDcn7N6B33gw6v4S4fphAVhAD4+gMO8Sei5oCcMpbqymn9v3ls1mTSEdcU2MRjXZE17m/CnpgeOzA8RmMd5lTplJNN8aoSN20cdd1H3J7Io="
  skip_cleanup: true
  file_glob: true
  file: "*/target/matchmaking-.jar"
  on:
    repo: OrigamiDream/Matchmaking
    tags: true