language: java
install: true
jdk: openjdk8
dist: trusty
cache:
  directories:
  - "$HOME/.m2/repository"
jobs:
  include:
  - stage: test
    script:
    - "./mvnw clean verify"
deploy:
  provider: releases
  api_key:
    secure: "BYDQbEbIBMa/DIUIl/kfhnQBBl5/F+YG5fbjQJG6I2S+r73eBez/itC6uZSUBA9o7Y0pGtcGoZ2TdbLGG/U556hjBw6iirrj/lY/t9+4a2UbAWrX8oO0H3PhSvTH/WEIN5HXQDOtLGLZ2ghqzq1XTiF0nw7tUuIPPSGbmgP5gHF/+HjdcMwKbI5x/1E9OeD9L+tlRlbFdofgS13efg1u7XWXUnWKvJ0u/GoccR38nGlMRvRhrAqwoYVk5wyz7ehRzkmQfckrgD03lKIZ1nTIZ+SjOfiB/aL+GYDJatmgDCK7h7vhABGKp/uUzYe5ooK3lOJnXLxu8PohUWUE4XpXJXBH1sgzW0lIljmgkAgRqKQWnqyFbwPemyPQDUwmJhlzDG/oTx44cbDYgZErafZTq3nvGw1Ryag7Vd4mBogxUISsDyvObrwU0zCxd+pVA1Q65Tg0dJKENM4wE7/nVcBTGUW2i0ZuDkpY+ckNgwbeMHL2GwnPjaSzvvkvE+UEjxI0FbgUFV3/hA3VkLMEjL4QQJNhFogLBN3ri6jF5TkWenBOFxH4mxqXdjdPgOAAJOCZb1R7gUBoZQl8sMS+zzB6bEAb/70gCy2vDK2F678XpUl8V2LHYstjklisY9M9EMfIIgHkK9KjiN1C5K6FMmL0lWLtAR4qKujMj0mqRGKR82A="
  skip_cleanup: true
  file_glob: true
  file: "*/target/matchmaking-.jar"
  on:
    repo: OrigamiDream/Matchmaking
    tags: true