name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build on ubuntu env
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: mvnw package
      run: ./mvnw clean package
